In [1]:
%run main_proyecto.py --parte3

    PROYECTO REDES NEURONALES - CLASIFICACIÓN MNIST
      Replicando la presentación del instructor
Fecha: 2025-09-19 01:46:31

Verificando requisitos...
Archivos de datos: OK
DnnLib: OK
Todos los requisitos OK


Demostración DnnLib:
------------------------------

Error inesperado: name 'np' is not defined


SystemExit: 1

In [2]:
%run main_proyecto.py --completo

    PROYECTO REDES NEURONALES - CLASIFICACIÓN MNIST
      Replicando la presentación del instructor
Fecha: 2025-09-19 01:46:59

Verificando requisitos...
Archivos de datos: OK
DnnLib: OK
Todos los requisitos OK


Demostración DnnLib:
------------------------------

Error inesperado: name 'np' is not defined


SystemExit: 1

In [3]:
%run main_proyecto.py --parte4

    PROYECTO REDES NEURONALES - CLASIFICACIÓN MNIST
      Replicando la presentación del instructor
Fecha: 2025-09-19 01:47:13

Verificando requisitos...
Archivos de datos: OK
DnnLib: OK
Todos los requisitos OK


Demostración DnnLib:
------------------------------

Error inesperado: name 'np' is not defined


SystemExit: 1

In [4]:
%run main_proyecto.py --completo

    PROYECTO REDES NEURONALES - CLASIFICACIÓN MNIST
      Replicando la presentación del instructor
Fecha: 2025-09-19 01:49:34

Verificando requisitos...
Archivos de datos: OK
DnnLib: OK
Todos los requisitos OK


Demostración DnnLib:
------------------------------
>>> import DnnLib
>>> out_logits = [np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(3.2), np.float64(3.3), np.float64(4.0), np.float64(2.4), np.float64(1.7)]
>>> out_probs = DnnLib.softmax(out_logits)
>>> out_probs
array([0.01777429 0.04831554 0.13133526 0.16041325 0.17728406 0.35700625
 0.07207832 0.03579303])
>>> sum(out_probs)
np.float32(1.0)

Modo: Proyecto completo (Parte 3 + Parte 4)

   PARTE 3: ENTRENAMIENTO BÁSICO
Replicando el entrenamiento mostrado en clase...
Train MNIST MLP model
Loading data...
Error en Parte 3: module 'DnnLib' has no attribute 'Adam'


SystemExit: 1

In [5]:
import DnnLib
print("Atributos disponibles en DnnLib:")
attrs = [attr for attr in dir(DnnLib) if not attr.startswith('_')]
for attr in sorted(attrs):
    print(f"  - {attr}")

Atributos disponibles en DnnLib:
  - ActivationType
  - DenseLayer
  - RELU
  - SIGMOID
  - SOFTMAX
  - TANH
  - apply_activation
  - apply_activation_derivative
  - relu
  - relu_derivative
  - sigmoid
  - sigmoid_derivative
  - softmax
  - softmax_derivative
  - tanh
  - tanh_derivative


In [6]:
%run main_proyecto.py --completo

    PROYECTO REDES NEURONALES - CLASIFICACIÓN MNIST
      Replicando la presentación del instructor
Fecha: 2025-09-19 01:51:50

Verificando requisitos...
Archivos de datos: OK
DnnLib: OK
Todos los requisitos OK


Demostración DnnLib:
------------------------------
>>> import DnnLib
>>> out_logits = [np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(3.2), np.float64(3.3), np.float64(4.0), np.float64(2.4), np.float64(1.7)]
>>> out_probs = DnnLib.softmax(out_logits)
>>> out_probs
array([0.01777429 0.04831554 0.13133526 0.16041325 0.17728406 0.35700625
 0.07207832 0.03579303])
>>> sum(out_probs)
np.float32(1.0)

Modo: Proyecto completo (Parte 3 + Parte 4)

   PARTE 3: ENTRENAMIENTO BÁSICO
Replicando el entrenamiento mostrado en clase...
Train MNIST MLP model
Loading data...
Error en Parte 3: module 'DnnLib' has no attribute 'Adam'


SystemExit: 1

In [7]:
%run main_proyecto.py --completo

    PROYECTO REDES NEURONALES - CLASIFICACIÓN MNIST
      Replicando la presentación del instructor
Fecha: 2025-09-19 01:55:24

Verificando requisitos...
Archivos de datos: OK
DnnLib: OK
Todos los requisitos OK


Demostración DnnLib:
------------------------------
>>> import DnnLib
>>> out_logits = [np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(3.2), np.float64(3.3), np.float64(4.0), np.float64(2.4), np.float64(1.7)]
>>> out_probs = DnnLib.softmax(out_logits)
>>> out_probs
array([0.01777429 0.04831554 0.13133526 0.16041325 0.17728406 0.35700625
 0.07207832 0.03579303])
>>> sum(out_probs)
np.float32(1.0)

Modo: Proyecto completo (Parte 3 + Parte 4)

   PARTE 3: ENTRENAMIENTO BÁSICO
Replicando el entrenamiento mostrado en clase...
Train MNIST MLP model
Loading data...
Error en Parte 3: module 'DnnLib' has no attribute 'Adam'


SystemExit: 1

In [8]:
%run main_proyecto.py --completo

    PROYECTO REDES NEURONALES - CLASIFICACIÓN MNIST
      Replicando la presentación del instructor
Fecha: 2025-09-19 01:57:21

Verificando requisitos...
Archivos de datos: OK
DnnLib: OK
Todos los requisitos OK


Demostración DnnLib:
------------------------------
>>> import DnnLib
>>> out_logits = [np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(3.2), np.float64(3.3), np.float64(4.0), np.float64(2.4), np.float64(1.7)]
>>> out_probs = DnnLib.softmax(out_logits)
>>> out_probs
array([0.01777429 0.04831554 0.13133526 0.16041325 0.17728406 0.35700625
 0.07207832 0.03579303])
>>> sum(out_probs)
np.float32(1.0)

Modo: Proyecto completo (Parte 3 + Parte 4)

   PARTE 3: ENTRENAMIENTO BÁSICO
Replicando el entrenamiento mostrado en clase...
Train MNIST MLP model
Loading data...
Error en Parte 3: module 'DnnLib' has no attribute 'Adam'


SystemExit: 1

In [9]:
%run main_proyecto.py

    PROYECTO REDES NEURONALES - CLASIFICACIÓN MNIST
      Replicando la presentación del instructor
Fecha: 2025-09-19 01:58:46

Verificando requisitos...
Archivos de datos: OK
DnnLib: OK
Todos los requisitos OK


Demostración DnnLib:
------------------------------
>>> import DnnLib
>>> out_logits = [np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(3.2), np.float64(3.3), np.float64(4.0), np.float64(2.4), np.float64(1.7)]
>>> out_probs = DnnLib.softmax(out_logits)
>>> out_probs
array([0.01777429 0.04831554 0.13133526 0.16041325 0.17728406 0.35700625
 0.07207832 0.03579303])
>>> sum(out_probs)
np.float32(1.0)

Modo: Proyecto completo (Parte 3 + Parte 4)

   PARTE 3: ENTRENAMIENTO BÁSICO
Replicando el entrenamiento mostrado en clase...
Train MNIST MLP model
Loading data...
Error en Parte 3: module 'DnnLib' has no attribute 'Adam'


SystemExit: 1